# Stage 1: Build the React application
FROM node:16 as builder

# Set working directory
WORKDIR /app

# Copies package.json and package-lock.json to Docker environment
COPY package*.json ./

# Install all node packages
RUN npm install --force

# Copy the src and public directory contents to the Docker environment
COPY public ./public
COPY src ./src

# Build the project
RUN yarn build

# Stage 2: Serve the app with nginx
FROM nginx:stable-alpine

# Copy the build output to replace the default nginx contents.
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80 to the outside once the container has launched
EXPOSE 80

# Define the command to run your app using CMD which defines your runtime
CMD ["nginx", "-g", "daemon off;"]