version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3001:3000"
    networks:
      - wikirace-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:80"
    networks:
      - wikirace-network

networks:
  wikirace-network:
    driver: bridge